trigger:
  branches:
    include:
      - main # Or the branch you want to trigger the pipeline

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Logging into Docker Hub..."
      docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    displayName: "Login to Docker Hub"

  - script: |
      echo "Building Docker image..."
      docker build -t stefanprodan/podinfo:v6.5.1 .
    displayName: "Build Docker image"

  - script: |
      echo "Pushing Docker image to Docker Hub..."
      docker push wasshaik/wefox-challenge:stefanprodan/podinfo:v6.5.1
    displayName: "Push Docker image"
